# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: net-ssh-multi 1.3.0.rc1 ruby lib

Gem::Specification.new do |s|
  s.name = "net-ssh-multi"
  s.version = "1.3.0.rc1"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jamis Buck", "Delano Mandelbaum"]
  s.cert_chain = ["gem-public_cert.pem"]
  s.date = "2016-03-24"
  s.description = "Control multiple Net::SSH connections via a single interface."
  s.email = "net-ssh@solutious.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".travis.yml",
    "CHANGES.txt",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "gem-public_cert.pem",
    "lib/net/ssh/multi.rb",
    "lib/net/ssh/multi/channel.rb",
    "lib/net/ssh/multi/channel_proxy.rb",
    "lib/net/ssh/multi/dynamic_server.rb",
    "lib/net/ssh/multi/pending_connection.rb",
    "lib/net/ssh/multi/server.rb",
    "lib/net/ssh/multi/server_list.rb",
    "lib/net/ssh/multi/session.rb",
    "lib/net/ssh/multi/session_actions.rb",
    "lib/net/ssh/multi/subsession.rb",
    "lib/net/ssh/multi/version.rb",
    "net-ssh-multi.gemspec",
    "test/channel_test.rb",
    "test/common.rb",
    "test/multi_test.rb",
    "test/server_test.rb",
    "test/session_actions_test.rb",
    "test/session_test.rb",
    "test/test_all.rb"
  ]
  s.homepage = "https://github.com/net-ssh/net-ssh-multi"
  s.licenses = ["MIT"]
  s.rubyforge_project = "net-ssh-multi"
  s.rubygems_version = "2.4.6"
  s.signing_key = "/mnt/gem/net-ssh-private_key.pem"
  s.summary = "Control multiple Net::SSH connections via a single interface."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<net-ssh>, [">= 2.6.5"])
      s.add_runtime_dependency(%q<net-ssh-gateway>, [">= 1.2.0"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
    else
      s.add_dependency(%q<net-ssh>, [">= 2.6.5"])
      s.add_dependency(%q<net-ssh-gateway>, [">= 1.2.0"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
    end
  else
    s.add_dependency(%q<net-ssh>, [">= 2.6.5"])
    s.add_dependency(%q<net-ssh-gateway>, [">= 1.2.0"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
  end
end
